#ifndef ASSIGNMENT3_TWODIMENSIONALLOGARITHMMOTIONSEARCH_H
#define ASSIGNMENT3_TWODIMENSIONALLOGARITHMMOTIONSEARCH_H

#include "MotionSearch.h"

class TwoDimensionalLogarithmMotionSearch : public MotionSearch{

};


#endif //ASSIGNMENT3_TWODIMENSIONALLOGARITHMMOTIONSEARCH_H
